### ISSUE TITLE
Field 'shape' of type is required but missing.

### ISSUE THREAD

**Issue by gaodashanfg** [daquexian/onnx-simplifier#45]
use onnx-simplifier-0.2.4 to simplify a cnn model, as follows:
python -m onnxsim cnn.onnx cnn_s.onnx
the result is failed, because the issue "onnx.onnx_cpp2py_export.checker.ValidationError: Field 'shape' of type is required but missing."

**Comment by daquexian** [comment]
Could you please send your model to daquexian566@gmail.com? Thanks!

**Comment by daquexian** [comment]
Thanks for your model!

It is a known issue of ONNX that has been fixed in https://github.com/onnx/onnx/pull/2574. The patch will be included in ONNX 1.7. As a temporary workaround for now, you can run
```bash
python3 -c "import onnxsim; print(onnxsim.__file__)"
```
to get the directory of onnxsim, and delete `'eliminate_identity'` in `onnx-simplifier.py` in the direcotry
